###################################################################
# This file is generated by a puppet class. Do not edit manually.

# Puppet class: ${puppetClassName}  
# Time        : ${timestamp?datetime}
# 
##################################################################

<#assign keys = props?keys>
<#list keys as key>
${key}=${props[key]}
</#list>
